version: '2'

services:
  web:
    env_file:
     - .env
    restart: always
    build: ./web
    expose:
      - "${WEB_PORT}"
    ports:
      - "${WEB_PORT}:8000"
    command: /usr/local/bin/gunicorn --log-file=- --capture-output --config gunicorn.conf -w 2 -b :8000 app:application
  worker:
    env_file:
     - .env
    restart: always
    build: ./web
    command: celery -A celery_worker.celery worker
  beat:
    env_file:
     - .env
    restart: always
    build: ./web
    command: celery --pidfile= -A celery_worker.celery beat
