services:
  web:
    env_file:
     - .env
    restart: always
    image: lcbruit/genvasc_portal_web:latest
    expose:
      - "${WEB_PORT}"
    ports:
      - "${WEB_PORT}:8080"
  worker:
    env_file:
     - .env
    restart: always
    image: lcbruit/genvasc_portal_celery:latest
    command: worker
  beat:
    env_file:
     - .env
    restart: always
    image: lcbruit/genvasc_portal_celery:latest
    command: beat --pidfile=
